### ISSUE TITLE
Doors with walls behind them

### ISSUE THREAD

**Issue by josephcsible** [McJty/LostCities#78]
![2018-01-27_18 01 57](https://user-images.githubusercontent.com/16061266/35477269-7add2a58-038d-11e8-925f-e8053df4f230.png)
![2018-01-27_18 02 18](https://user-images.githubusercontent.com/16061266/35477270-7cf8f8d0-038d-11e8-821d-e7971050478c.png)
"Space" preset.

**Comment by McJty** [comment]
Is this with latest alpha? Because that should have been fixed

**Comment by josephcsible** [comment]
Yep, that was 2.0.0alpha5.

**Comment by McJty** [comment]
I cannot reproduce this. Are you sure you regenerated the world? Also fresh configs?

**Comment by josephcsible** [comment]
With Forge 2604, no other mods, and a freshly-generated config file, I still reproduce it.

**Comment by josephcsible** [comment]
Fixed now, presumably by 25730cc
